---
abstract: 'YAML::PP with CourtIO::YAML::PP::Schema::Include'
author:
  - 'CourtAPI Team <support@courtapi.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CourtIO-YAML-PP
requires:
  Fatal: '0'
  File::Basename: '0'
  File::Slurp: '0'
  File::Spec: '0'
  JSON::XS: '0'
  Log::Log4perl: '0'
  Log::Log4perl::Appender::ScreenColoredLevels: '0'
  Moo: '0'
  MooX::Cmd: '0'
  MooX::Options: '0'
  YAML::PP: '0.021'
  YAML::PP::Common: '0'
  namespace::clean: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  strictures: '2'
  warnings: '0'
resources:
  bugtracker: https://github.com/CourtAPI/courtio-yaml-include/issues
  homepage: https://github.com/CourtAPI/courtio-yaml-include
  repository: https://github.com/CourtAPI/courtio-yaml-include.git
version: '0.07'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
